apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whoosh-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: whoosh
  storageClassName: standard
